name: Build Mod
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 拉取代码到 runner

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew  # 关键步骤：为 gradlew 赋予执行权限

      - name: Clean and build
        run: |
          # 现在可以正常执行 gradlew 命令了
          ./gradlew clean
          ./gradlew build --refresh-dependencies --console plain
        env:
          MAVEN_MIRROR: https://maven.aliyun.com/repository/public
    
