name: Build Fabric Mod

on:
  push:
    branches: [ main ]  # 提交到main分支时触发编译
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # 使用Ubuntu系统，编译速度快
    
    steps:
    - uses: actions/checkout@v4  # 拉取仓库代码
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'  # 使用Eclipse Temurin JDK（Fabric推荐）
        cache: gradle  # 缓存Gradle依赖，加速下次编译
    
    - name: Make Gradle wrapper executable
      run: chmod +x ./gradlew  # 赋予Gradle执行权限（Linux系统必需）
    
    - name: Build with Gradle
      run: ./gradlew build  # 执行编译命令（同本地的gradlew build）
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Mod JAR File  # 下载时的文件包名
        path: build/libs/*.jar  # 编译后JAR文件的路径（Fabric默认输出目录）
